### Register User API
POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json

{
    "username" : "ronaldo",
    "password": "1212",
    "name": "c. ronaldo"
}

### Login User API
POST http://localhost:8000/api/users/login
Content-Type: application/json
Accept: application/json

{
    "username": "messi",
    "password": "121212"
}

### Get Current User API
GET http://localhost:8000/api/users/current
Accept: application/json
Authorization: 3542fbc3-bf40-4b2e-b3a8-eda083057983

### Update Current User API
PATCH http://localhost:8000/api/users/current
Content-Type: application/json
Accept: application/json
Authorization: 3542fbc3-bf40-4b2e-b3a8-eda083057983

{
    "name" : "messo oo"
}



